### ISSUE TITLE
You've stopped working on and streaming development of this codebase

### ISSUE THREAD

**Issue by naikrovek** [Tesserex/C--MegaMan-Engine#12]
pls fix

**Comment by KCreator** [comment]
While development does seem to have slowed down a bit, Tesserex does still support this project, The rapid reply to my issue certainly proved that. Please be patient, as programmers have lives too :P

**Comment by Tesserex** [comment]
yeah!

**Comment by naikrovek** [comment]
Well, I know you're busy, but there's no other way for us plebes to contact
you.  The site linked in the repo description 404s.

Couldn't think of another way to express interest in future streams...

**Comment by Tesserex** [comment]
I'll try to find some time but it has been harder the past few months. I did work on it recently though.
